from __future__ import annotations

import unittest
from pathlib import Path
from unittest.mock import patch

import agents
from tools.llm_client import LLMClient


HIGH_LEVEL_AGENTS = {
    "ResearchUnderstandingAgent",
    "RepositoryUnderstandingAgent",
    "ReproductionPlannerAgent",
    "ExecutionDiagnosisAgent",
    "ResearchSynthesizerAgent",
    "ProductPlannerAgent",
    "PrototypeBuilderAgent",
    "ProductEvaluatorAgent",
}


class AgentArchitectureTests(unittest.TestCase):
    def test_agents_package_exports_only_high_level_agents_and_base(self) -> None:
        self.assertEqual(set(agents.__all__), {"BaseAgent", *HIGH_LEVEL_AGENTS})
        for legacy_name in (
            "PaperReaderAgent",
            "MethodExtractorAgent",
            "RepoAnalyzerAgent",
            "EnvironmentAgent",
            "ExperimentPlannerAgent",
            "RunnerAgent",
            "DebugAgent",
            "ReportAgent",
            "CodeAgent",
        ):
            self.assertFalse(hasattr(agents, legacy_name), legacy_name)

    def test_fragmented_agents_are_not_top_level_files(self) -> None:
        root = Path(agents.__file__).resolve().parent
        expected = {
            "__init__.py",
            "base_agent.py",
            "structured_agent.py",
            "research_understanding_agent.py",
            "repository_understanding_agent.py",
            "reproduction_planner_agent.py",
            "execution_diagnosis_agent.py",
            "research_synthesizer_agent.py",
            "product_planner_agent.py",
            "prototype_builder_agent.py",
            "product_evaluator_agent.py",
        }
        self.assertEqual({path.name for path in root.glob("*.py")}, expected)
        self.assertTrue((root / "legacy").is_dir())

    def test_active_code_does_not_import_legacy_agents(self) -> None:
        project_root = Path(agents.__file__).resolve().parent.parent
        active_paths = [
            project_root / "app.py",
            project_root / "main.py",
            *project_root.joinpath("pipeline").glob("*.py"),
            *project_root.joinpath("productize").glob("*.py"),
            *(
                path
                for path in project_root.joinpath("agents").glob("*.py")
                if path.name != "__init__.py"
            ),
        ]
        for path in active_paths:
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertNotIn("agents.legacy", text)

    def test_high_level_reproduce_agents_return_structured_mock_outputs(self) -> None:
        client = LLMClient(mock_mode=True)
        research = agents.ResearchUnderstandingAgent(client).run_structured(
            {"paper_text": "A paper about image classification."}
        )
        repository = agents.RepositoryUnderstandingAgent(client).run_structured(
            {"research_understanding": research.model_dump(), "repo_scan": {}}
        )
        plan = agents.ReproductionPlannerAgent(client).run_structured(
            {
                "research_understanding": research.model_dump(),
                "repository_understanding": repository.model_dump(),
                "goal": "minimal training experiment",
                "hardware": "CPU only",
            }
        )
        diagnosis = agents.ExecutionDiagnosisAgent(client).run_structured(
            {"command_results": [], "reproduction_plan": plan.model_dump()}
        )
        self.assertTrue(research.method_modules)
        self.assertEqual(repository.repo_source, "paper-only")
        self.assertTrue(plan.minimal_reproduction_steps)
        self.assertEqual(diagnosis.feasibility, "planned_not_executed")

    def test_active_pipeline_uses_only_four_high_level_reproduce_agents(self) -> None:
        from pipeline.reproduce_pipeline import run_reproduce_pipeline

        with (
            patch("pipeline.reproduce_pipeline.parse_pdf", return_value="paper text"),
            patch("pipeline.reproduce_pipeline.save_output"),
        ):
            result = run_reproduce_pipeline(
                pdf_path="paper.pdf",
                github_url="",
                llm_client=LLMClient(mock_mode=True),
            )

        self.assertEqual(result["repo_source"], "Paper only")
        self.assertEqual(result["repo_path"], "")
        self.assertTrue(result["research_understanding"])
        self.assertTrue(result["repository_understanding"])
        self.assertTrue(result["reproduction_plan"])
        self.assertTrue(result["execution_diagnosis"])
        self.assertNotIn("Generated by Code Agent", result["code_info"])


if __name__ == "__main__":
    unittest.main()
