from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import main as pipeline
from agents.code_agent import CodeAgent
from tools.llm_client import LLMClient


class FakeLLMClient:
    mock_mode = False

    def __init__(self, response: dict[str, object]) -> None:
        self.response = response

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        return json.dumps(self.response)


class CodeAgentTests(unittest.TestCase):
    def test_generate_repository_writes_valid_bundle(self) -> None:
        response = {
            "project_name": "demo",
            "summary": "A minimal demo.",
            "files": [
                {"path": "README.md", "content": "# Demo\n"},
                {"path": "main.py", "content": "print('ok')\n"},
            ],
        }
        with tempfile.TemporaryDirectory() as temp_dir:
            generated = CodeAgent(
                FakeLLMClient(response),
                workspace_dir=temp_dir,
            ).generate_repository({"method_info": "demo"})

            root = Path(generated["repo_path"])
            self.assertEqual((root / "main.py").read_text(encoding="utf-8"), "print('ok')\n")
            self.assertTrue((root / "CODE_AGENT_MANIFEST.json").is_file())

    def test_generate_repository_rejects_path_traversal(self) -> None:
        response = {
            "files": [{"path": "../outside.py", "content": "print('unsafe')\n"}],
        }
        with tempfile.TemporaryDirectory() as temp_dir:
            agent = CodeAgent(FakeLLMClient(response), workspace_dir=temp_dir)
            with self.assertRaisesRegex(ValueError, "Unsafe generated file path"):
                agent.generate_repository({"method_info": "demo"})
            self.assertEqual(list(Path(temp_dir).iterdir()), [])

    def test_generate_repository_rejects_windows_reserved_name(self) -> None:
        response = {
            "files": [{"path": "CON.py", "content": "print('unsafe')\n"}],
        }
        with tempfile.TemporaryDirectory() as temp_dir:
            agent = CodeAgent(FakeLLMClient(response), workspace_dir=temp_dir)
            with self.assertRaisesRegex(ValueError, "Unsafe generated file path"):
                agent.generate_repository({"method_info": "demo"})
            self.assertEqual(list(Path(temp_dir).iterdir()), [])

    def test_pipeline_generates_code_when_github_url_is_empty(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            client = LLMClient(mock_mode=True)

            def code_agent_factory(llm_client: LLMClient) -> CodeAgent:
                return CodeAgent(llm_client, workspace_dir=temp_dir)

            with (
                patch.object(pipeline, "parse_pdf", return_value="paper text"),
                patch.object(pipeline, "CodeAgent", side_effect=code_agent_factory),
                patch.object(pipeline, "_save_output"),
            ):
                result = pipeline.run_paperpilot(
                    pdf_path="paper.pdf",
                    hardware="CPU only",
                    gpu_info="",
                    goal="minimal training experiment",
                    llm_client=client,
                )

            self.assertEqual(result["repo_source"], "Generated by Code Agent")
            self.assertTrue(Path(result["repo_path"], "main.py").is_file())
            self.assertIn("Mock mode generated", result["code_info"])

    def test_pipeline_keeps_clone_path_when_github_url_is_provided(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            Path(temp_dir, "README.md").write_text("# Existing repository\n", encoding="utf-8")

            def fake_clone(result: dict[str, object], github_url: str) -> str:
                result["repo_path"] = temp_dir
                return temp_dir

            with (
                patch.object(pipeline, "parse_pdf", return_value="paper text"),
                patch.object(pipeline, "_do_clone", side_effect=fake_clone),
                patch.object(pipeline, "CodeAgent") as code_agent,
                patch.object(pipeline, "_save_output"),
            ):
                result = pipeline.run_paperpilot(
                    pdf_path="paper.pdf",
                    github_url="https://github.com/owner/repository",
                    llm_client=LLMClient(mock_mode=True),
                )

            code_agent.assert_not_called()
            self.assertEqual(result["repo_source"], "GitHub repository")
            self.assertEqual(result["repo_path"], temp_dir)


if __name__ == "__main__":
    unittest.main()
