"""Repository acquisition stage: clone, generate code, and scan."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

from agents import CodeAgent, RepoCloneAgent
from tools.github_tool import is_valid_github_url
from tools.repo_scanner import scan_repo


def do_clone(result: dict[str, Any], github_url: str) -> str:
    """Clone a public GitHub repo and record the path in result."""
    if not is_valid_github_url(github_url):
        result["errors"].append(
            "[GitHub URL validation failed] Only https://github.com/owner/repo format is supported."
        )
        return ""
    try:
        repo_clone_agent = RepoCloneAgent()
        repo_path = repo_clone_agent.clone(github_url)
        result["repo_path"] = str(repo_path)
        return str(repo_path)
    except Exception as exc:
        result["errors"].append(f"[Repo Clone Agent] {exc}")
        return ""


def do_generate_code(
    result: dict[str, Any],
    llm_client: Any,
    context: dict[str, Any],
) -> str:
    """Generate a reproduction repository via CodeAgent."""
    try:
        generated = CodeAgent(llm_client).generate_repository(context)
        result["repo_path"] = str(generated["repo_path"])
        result["repo_source"] = "Generated by Code Agent"
        generated_files = "\n".join(
            f"- `{path}`" for path in generated.get("files", [])
        )
        result["code_info"] = (
            f"{generated.get('summary', 'Code Agent generated a reproduction project.')}"
            f"\n\nGenerated files:\n{generated_files}"
        )
        return result["repo_path"]
    except Exception as exc:
        result["errors"].append(f"[Code Agent] {exc}")
        return ""


def prepare_repository(
    result: dict[str, Any],
    github_url: str,
    llm_client: Any,
    code_context: dict[str, Any],
    progress_callback: Callable[[str], None] | None,
) -> dict[str, Any] | None:
    """Acquire and scan a repository, either by cloning or generating code."""
    if github_url.strip():
        if progress_callback:
            progress_callback("Repo Clone Agent cloning repository")
        repo_path = do_clone(result, github_url.strip())
        if repo_path:
            result["repo_source"] = "GitHub repository"
    else:
        if progress_callback:
            progress_callback("Code Agent generating reproduction code")
        repo_path = do_generate_code(result, llm_client, code_context)

    if not repo_path:
        return None
    try:
        repo_scan = scan_repo(repo_path)
    except Exception as exc:
        result["errors"].append(f"[Repo Scanner] {exc}")
        return None
    repo_scan["repository_source"] = result["repo_source"]
    if result["code_info"]:
        repo_scan["code_generation"] = result["code_info"]
    return repo_scan
