"""Deterministic templates for generated PaperPilot product prototypes."""

from __future__ import annotations

import re
from pathlib import Path

SUPPORTED_TEMPLATES = ("image", "text", "video", "file")

_TEMPLATE_KEYWORDS = {
    "image": (
        "image",
        "vision",
        "classification",
        "detection",
        "segmentation",
        "ocr",
        "medical imaging",
        "图像",
        "视觉",
    ),
    "text": (
        "text",
        "language",
        "question answering",
        "rag",
        "translation",
        "summarization",
        "information extraction",
        "文本",
        "问答",
        "翻译",
    ),
    "video": (
        "video",
        "tracking",
        "action recognition",
        "world model",
        "object-centric",
        "temporal",
        "视频",
        "跟踪",
    ),
}

_INPUT_BLOCKS = {
    "image": """
uploaded = st.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])
input_data = uploaded
if uploaded is not None:
    st.image(uploaded, caption="Input image")
run_disabled = uploaded is None
button_label = "Run Model"
""",
    "text": """
input_data = st.text_area("Input text", height=220)
run_disabled = not input_data.strip()
button_label = "Run Model"
""",
    "video": """
uploaded = st.file_uploader("Upload a video", type=["mp4", "mov", "avi"])
input_data = uploaded
if uploaded is not None:
    st.video(uploaded)
run_disabled = uploaded is None
button_label = "Analyze"
""",
    "file": """
uploaded = st.file_uploader("Upload a file")
input_data = uploaded
run_disabled = uploaded is None
button_label = "Analyze"
""",
}

_MOCK_RESULTS = {
    "image": """{
            "type": "image",
            "message": "Mock image prediction completed.",
            "result": {"label": "demo_object", "confidence": 0.95},
        }""",
    "text": """{
            "type": "text",
            "result": "This is a mock response generated by the product prototype.",
        }""",
    "video": """{
            "type": "video",
            "report": (
                "Mock video analysis completed. Key objects and temporal "
                "patterns would be shown here."
            ),
        }""",
    "file": """{
            "type": "file",
            "report": (
                "Mock file analysis completed. The generated report would "
                "be shown here."
            ),
        }""",
}


def _normalize_template(template_type: str) -> str:
    normalized = template_type.strip().lower()
    if normalized not in SUPPORTED_TEMPLATES:
        raise ValueError(
            f"Unsupported template_type: {template_type}. "
            f"Expected one of {SUPPORTED_TEMPLATES}."
        )
    return normalized


def select_product_template(
    paper_info: str,
    method_info: str,
    repo_info: str,
    product_spec: str,
    preferred_type: str = "auto",
) -> str:
    """Choose one supported product template from user preference and evidence."""
    preference = preferred_type.strip().lower()
    if preference != "auto":
        if preference not in SUPPORTED_TEMPLATES:
            raise ValueError(
                "preferred_type must be auto, image, text, video, or file."
            )
        return preference

    evidence = " ".join(
        (paper_info, method_info, repo_info, product_spec)
    ).lower()
    scores = {
        template: sum(evidence.count(keyword) for keyword in keywords)
        for template, keywords in _TEMPLATE_KEYWORDS.items()
    }
    best_score = max(scores.values(), default=0)
    if best_score == 0:
        return "file"
    for template in ("image", "text", "video"):
        if scores[template] == best_score:
            return template
    return "file"


def _extract_product_name(product_spec: str) -> str:
    match = re.search(
        r"##\s+Product Name\s*\n+\s*([^\n#]+)",
        product_spec,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1).strip()
    first_heading = re.search(r"^#\s+(.+)$", product_spec, flags=re.MULTILINE)
    if first_heading:
        return first_heading.group(1).strip()
    return "Generated Product Prototype"


def _extract_core_features(product_spec: str) -> list[str]:
    features: list[str] = []
    capture = False
    for line in product_spec.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("### core features"):
            capture = True
            continue
        if capture and stripped.startswith("#"):
            break
        if capture and stripped.startswith("- "):
            features.append(stripped[2:].strip())
    return features[:5]


def build_app_source(
    template_type: str,
    product_spec: str = "",
    frontend_plan: str = "",
) -> str:
    """Return a standalone Streamlit application for one product template."""
    template = _normalize_template(template_type)
    product_name = _extract_product_name(product_spec)
    core_features = _extract_core_features(product_spec) or [
        "Review input",
        "Run mock analysis",
        "Export structured findings",
    ]
    plan_excerpt = (frontend_plan or "Mock-first workflow").strip()[:1000]
    return f'''"""Generated PaperPilot {template} product prototype."""

from __future__ import annotations

import json

import streamlit as st

from adapter import ModelAdapter


PRODUCT_NAME = {product_name!r}
CORE_FEATURES = {core_features!r}
FRONTEND_PLAN = {plan_excerpt!r}


st.set_page_config(page_title=PRODUCT_NAME, layout="wide")
st.markdown("""
<style>
.pp-panel {{border: 1px solid #dde3ea; border-radius: 8px; padding: 1rem; background: #fbfcfe; min-height: 5.5rem;}}
.pp-muted {{color: #5f6b7a; font-size: 0.92rem;}}
</style>
""", unsafe_allow_html=True)

with st.sidebar:
    st.header("Run Settings")
    # ModelAdapter defaults to mock_mode=True; keep this visible for review.
    mock_mode = st.toggle("Mock mode", value=True)
    confidence_threshold = st.slider("Confidence threshold", 0.0, 1.0, 0.65, 0.05)
    output_detail = st.selectbox("Output detail", ["Concise", "Detailed"])
    st.caption("Real model integration requires manual adapter.py review.")

st.title(PRODUCT_NAME)
st.caption(
    "Mock-first research product prototype. It demonstrates the product "
    "workflow without importing or executing the source repository."
)

st.markdown("### Core Workflow")
feature_columns = st.columns(min(len(CORE_FEATURES), 3))
for index, feature in enumerate(CORE_FEATURES):
    with feature_columns[index % len(feature_columns)]:
        st.markdown(
            f"<div class='pp-panel'><strong>{{feature}}</strong></div>",
            unsafe_allow_html=True,
        )

{_INPUT_BLOCKS[template].strip()}

notes = st.text_area(
    "Decision context",
    placeholder="Optional constraints, user segment, or scenario.",
)

if st.button(button_label, type="primary", disabled=run_disabled):
    try:
        adapter = ModelAdapter(mock_mode=mock_mode)
        adapter.setup()
        adapter.load_model()
        result = adapter.predict(input_data)
    except Exception as exc:
        st.error(f"Product execution failed: {{exc}}")
    else:
        result.update(
            {{
                "confidence_threshold": confidence_threshold,
                "output_detail": output_detail,
                "notes": notes,
            }}
        )
        summary_tab, evidence_tab, export_tab = st.tabs(
            ["Summary", "Evidence & Limits", "Export"]
        )
        with summary_tab:
            metric_cols = st.columns(3)
            metric_cols[0].metric("Mode", "Mock" if mock_mode else "Manual integration")
            metric_cols[1].metric("Threshold", f"{{confidence_threshold:.2f}}")
            metric_cols[2].metric("Detail", output_detail)
            st.json(result)
        with evidence_tab:
            st.markdown("#### Prototype Plan")
            st.markdown(FRONTEND_PLAN)
            st.markdown("#### Limitations")
            st.markdown(
                "- Outputs are deterministic mock responses.\\n"
                "- Real checkpoints, datasets, and repository scripts are not executed.\\n"
                "- Adapter integration must be reviewed manually."
            )
        with export_tab:
            st.write("Download the structured mock result for review or demo notes.")
        result_json = json.dumps(result, ensure_ascii=False, indent=2)
        st.download_button(
            "Download result",
            data=result_json,
            file_name="product_result.json",
            mime="application/json",
        )
'''


def build_adapter_source(template_type: str, repo_path: str | Path) -> str:
    """Return a mock-first adapter without importing or executing source code."""
    template = _normalize_template(template_type)
    safe_repo_path = repr(str(repo_path))
    return f'''"""Mock-first adapter generated by PaperPilot."""

from __future__ import annotations

from pathlib import Path
from typing import Any


class ModelAdapter:
    def __init__(
        self,
        repo_path: str = {safe_repo_path},
        device: str = "cpu",
        mock_mode: bool = True,
    ) -> None:
        self.repo_path = Path(repo_path).expanduser()
        self.device = device
        self.mock_mode = mock_mode
        self.model: Any | None = None

    def setup(self) -> dict[str, Any]:
        """Check paths, dependencies, and runtime mode."""
        if not self.mock_mode and not self.repo_path.exists():
            raise FileNotFoundError(f"Repository path not found: {{self.repo_path}}")
        return {{
            "ready": True,
            "mock_mode": self.mock_mode,
            "repo_path": str(self.repo_path),
            "device": self.device,
        }}

    def load_model(self) -> Any | None:
        """Load a reviewed real integration or keep mock mode active."""
        if self.mock_mode:
            return None
        raise NotImplementedError(
            "Real model integration is not configured. Review the source "
            "repository inference code and implement it here manually."
        )

    def predict(self, input_data: Any) -> dict[str, Any]:
        """Run reviewed inference or return a deterministic mock result."""
        if not self.mock_mode:
            raise NotImplementedError(
                "Real prediction is not configured. Enable it only after "
                "manual review and implementation."
            )
        return {_MOCK_RESULTS[template]}
'''
