"""Deterministic templates for generated PaperPilot product prototypes."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from schemas.product_schema import ProductUISpec

SUPPORTED_TEMPLATES = ("image", "text", "video", "file")

_TEMPLATE_KEYWORDS = {
    "image": (
        "image",
        "vision",
        "classification",
        "detection",
        "segmentation",
        "ocr",
        "medical imaging",
        "图像",
        "视觉",
    ),
    "text": (
        "text",
        "language",
        "question answering",
        "rag",
        "translation",
        "summarization",
        "information extraction",
        "文本",
        "问答",
        "翻译",
    ),
    "video": (
        "video",
        "tracking",
        "action recognition",
        "world model",
        "object-centric",
        "temporal",
        "视频",
        "跟踪",
    ),
}

_INPUT_BLOCKS = {
    "image": """
uploaded = st.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])
input_data = uploaded
if uploaded is not None:
    st.image(uploaded, caption="Input image")
run_disabled = uploaded is None
button_label = "Run Model"
""",
    "text": """
input_data = st.text_area("Input text", height=220)
run_disabled = not input_data.strip()
button_label = "Run Model"
""",
    "video": """
uploaded = st.file_uploader("Upload a video", type=["mp4", "mov", "avi"])
input_data = uploaded
if uploaded is not None:
    st.video(uploaded)
run_disabled = uploaded is None
button_label = "Analyze"
""",
    "file": """
uploaded = st.file_uploader("Upload a file")
input_data = uploaded
run_disabled = uploaded is None
button_label = "Analyze"
""",
}

_MOCK_RESULTS = {
    "image": """{
            "type": "image",
            "message": "Mock image prediction completed.",
            "result": {"label": "demo_object", "confidence": 0.95},
        }""",
    "text": """{
            "type": "text",
            "result": "This is a mock response generated by the product prototype.",
        }""",
    "video": """{
            "type": "video",
            "report": (
                "Mock video analysis completed. Key objects and temporal "
                "patterns would be shown here."
            ),
        }""",
    "file": """{
            "type": "file",
            "report": (
                "Mock file analysis completed. The generated report would "
                "be shown here."
            ),
        }""",
}


def _normalize_template(template_type: str) -> str:
    normalized = template_type.strip().lower()
    if normalized not in SUPPORTED_TEMPLATES:
        raise ValueError(
            f"Unsupported template_type: {template_type}. "
            f"Expected one of {SUPPORTED_TEMPLATES}."
        )
    return normalized


def select_product_template(
    paper_info: str,
    method_info: str,
    repo_info: str,
    product_spec: str,
    preferred_type: str = "auto",
) -> str:
    """Choose one supported product template from user preference and evidence."""
    preference = preferred_type.strip().lower()
    if preference != "auto":
        if preference not in SUPPORTED_TEMPLATES:
            raise ValueError(
                "preferred_type must be auto, image, text, video, or file."
            )
        return preference

    evidence = " ".join(
        (paper_info, method_info, repo_info, product_spec)
    ).lower()
    scores = {
        template: sum(evidence.count(keyword) for keyword in keywords)
        for template, keywords in _TEMPLATE_KEYWORDS.items()
    }
    best_score = max(scores.values(), default=0)
    if best_score == 0:
        return "file"
    for template in ("image", "text", "video"):
        if scores[template] == best_score:
            return template
    return "file"


def _extract_product_name(product_spec: str) -> str:
    match = re.search(
        r"##\s+Product Name\s*\n+\s*([^\n#]+)",
        product_spec,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1).strip()
    first_heading = re.search(r"^#\s+(.+)$", product_spec, flags=re.MULTILINE)
    if first_heading:
        return first_heading.group(1).strip()
    return "Generated Product Prototype"


def _extract_core_features(product_spec: str) -> list[str]:
    features: list[str] = []
    capture = False
    for line in product_spec.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("### core features"):
            capture = True
            continue
        if capture and stripped.startswith("#"):
            break
        if capture and stripped.startswith("- "):
            features.append(stripped[2:].strip())
    return features[:5]


def _as_list(value: Any, fallback: list[str]) -> list[str]:
    if isinstance(value, list):
        items = [str(item).strip() for item in value if str(item).strip()]
        return items or fallback
    return fallback


def _clean_label(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()[:80] or "Input"


def _build_dynamic_input_block(user_inputs: list[str]) -> str:
    lines = [
        "context_values = {}",
        'st.markdown("### Task Setup")',
    ]
    for index, label in enumerate(user_inputs[:5], 1):
        safe_label = _clean_label(label)
        lowered = safe_label.lower()
        key = f"dynamic_input_{index}"
        if any(
            word in lowered
            for word in ("threshold", "confidence", "sensitivity", "score")
        ):
            lines.append(
                f"context_values[{safe_label!r}] = st.slider({safe_label!r}, 0.0, 1.0, 0.65, 0.05, key={key!r})"
            )
        elif any(
            word in lowered
            for word in ("mode", "type", "selector", "category", "module")
        ):
            lines.append(
                f"context_values[{safe_label!r}] = st.selectbox({safe_label!r}, [\"Default\", \"Focused\", \"Broad\"], key={key!r})"
            )
        else:
            lines.append(
                f"context_values[{safe_label!r}] = st.text_input({safe_label!r}, key={key!r})"
            )
    return "\n".join(lines)


def _build_ui_spec_input_block(spec: ProductUISpec) -> str:
    lines = [
        "context_values = {}",
        'st.markdown("### Task Setup")',
    ]
    used_control_ids: set[str] = set()
    for index, control in enumerate(spec.input_controls[:8], 1):
        base_control_id = control.control_id or f"control_{index}"
        control_id = base_control_id
        suffix = 2
        while control_id in used_control_ids:
            control_id = f"{base_control_id}_{suffix}"
            suffix += 1
        used_control_ids.add(control_id)
        label = _clean_label(control.label or control_id.replace("_", " ").title())
        default = control.default
        options = [str(option) for option in control.options] or ["Default"]
        key = f"ui_control_{control_id}"
        if control.control_type == "slider":
            slider_default = default if isinstance(default, (int, float)) else 0.5
            slider_default = min(max(float(slider_default), 0.0), 1.0)
            lines.append(
                f"context_values[{control_id!r}] = st.slider({label!r}, 0.0, 1.0, {slider_default!r}, 0.05, key={key!r})"
            )
        elif control.control_type == "selectbox":
            lines.append(
                f"context_values[{control_id!r}] = st.selectbox({label!r}, {options!r}, key={key!r})"
            )
        elif control.control_type == "textarea":
            lines.append(
                f"context_values[{control_id!r}] = st.text_area({label!r}, value={str(default or '')!r}, key={key!r})"
            )
        else:
            lines.append(
                f"context_values[{control_id!r}] = st.text_input({label!r}, value={str(default or '')!r}, key={key!r})"
            )
    if not spec.input_controls:
        lines.append('st.caption("No additional controls were specified.")')
    return "\n".join(lines)


def _build_ui_spec_result_block(spec: ProductUISpec) -> str:
    lines: list[str] = []
    for index, component in enumerate(spec.result_components[:8], 1):
        label = _clean_label(component.label or f"Result {index}")
        source_key = component.source_key or component.component_id or f"result_{index}"
        fallback = component.description or "Not available in mock result."
        if component.component_type == "metric":
            lines.append(
                f"st.metric({label!r}, result.get({source_key!r}, {fallback!r}))"
            )
        elif component.component_type == "table":
            lines.append(
                f"st.dataframe(result.get({source_key!r}, []), use_container_width=True)"
            )
        else:
            lines.append(f"st.markdown({('#### ' + label)!r})")
            lines.append(
                f"st.write(result.get({source_key!r}, {fallback!r}))"
            )
    if not lines:
        lines.append('st.markdown("#### Summary")')
        lines.append('st.write(result.get("result", result))')
    return "\n".join(lines)


def _indent_block(source: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(
        f"{prefix}{line}" if line else line for line in source.splitlines()
    )


def build_app_source(
    template_type: str,
    product_spec: str = "",
    frontend_plan: str = "",
    prototype_plan: dict[str, Any] | None = None,
    ui_spec: dict[str, Any] | None = None,
) -> str:
    """Return a standalone Streamlit application for one product template."""
    template = _normalize_template(template_type)
    if ui_spec is not None:
        spec = ProductUISpec.model_validate(ui_spec)
        product_name = spec.product_name or _extract_product_name(product_spec)
        page_structure = spec.page_sections or [
            "Set up task",
            "Run mock analysis",
            "Review evidence and limitations",
        ]
        mock_schema = spec.mock_result_schema
        input_block = _build_ui_spec_input_block(spec)
        result_block = _build_ui_spec_result_block(spec)
        plan_excerpt = (frontend_plan or "Mock-first workflow").strip()[:1000]
        return f'''"""Generated PaperPilot {template} product prototype."""

from __future__ import annotations

import json

import streamlit as st

from adapter import ModelAdapter


PRODUCT_NAME = {product_name!r}
PAGE_STRUCTURE = {page_structure!r}
FRONTEND_PLAN = {plan_excerpt!r}
UI_SPEC = {spec.model_dump(mode="json")!r}
UI_SPEC_MARKERS = {{
    "structured_controls": True,
    "result_components": True,
    "state_copy": True,
    "mock_schema": True,
}}
MOCK_RESULT_SCHEMA = {mock_schema!r}


st.set_page_config(page_title=PRODUCT_NAME, layout="wide")
st.markdown("""
<style>
.pp-panel {{border: 1px solid #dde3ea; border-radius: 8px; padding: 1rem; background: #fbfcfe; min-height: 5.5rem;}}
.pp-muted {{color: #5f6b7a; font-size: 0.92rem;}}
</style>
""", unsafe_allow_html=True)

with st.sidebar:
    st.header("Run Settings")
    mock_mode = st.toggle("Mock mode", value=True)
    output_detail = st.selectbox("Output detail", ["Concise", "Detailed"])
    st.caption("Real model integration requires manual adapter.py review.")

st.title(PRODUCT_NAME)
st.caption(
    "Mock-first research product prototype. It demonstrates the product "
    "workflow without importing or executing the source repository."
)

st.markdown("### Core Workflow")
for step_number, section in enumerate(PAGE_STRUCTURE, 1):
    st.markdown(f"{{step_number}}. {{section}}")

{input_block}

input_data = context_values
run_disabled = False
button_label = "Run Model"

st.info({spec.states.empty!r})

if st.button(button_label, type="primary", disabled=run_disabled):
    try:
        with st.spinner({spec.states.loading!r}):
            adapter = ModelAdapter(mock_mode=mock_mode)
            adapter.setup()
            adapter.load_model()
            result = adapter.predict(input_data)
    except Exception as exc:
        st.error({spec.states.error!r})
        st.exception(exc)
    else:
        result.update(
            {{
                "output_detail": output_detail,
                "configured_inputs": context_values,
            }}
        )
        st.success({spec.states.success!r})
        summary_tab, evidence_tab, export_tab = st.tabs(
            ["Summary", "Evidence & Limits", "Export"]
        )
        with summary_tab:
{_indent_block(result_block, 12)}
            st.json(result)
        with evidence_tab:
            st.markdown("#### Mock Result Schema")
            st.json(MOCK_RESULT_SCHEMA)
            st.markdown("#### Prototype Plan")
            st.markdown(FRONTEND_PLAN)
            st.markdown("#### Limitations")
            st.markdown(
                "- Outputs are deterministic mock responses.\\n"
                "- Real checkpoints, datasets, and repository scripts are not executed.\\n"
                "- Adapter integration must be reviewed manually."
            )
        with export_tab:
            st.write("Download the structured mock result for review or demo notes.")
        result_json = json.dumps(result, ensure_ascii=False, indent=2)
        st.download_button(
            "Download result",
            data=result_json,
            file_name="product_result.json",
            mime="application/json",
        )
'''
    prototype_plan = prototype_plan or {}
    product_name = _extract_product_name(product_spec)
    core_features = _extract_core_features(product_spec) or [
        "Review input",
        "Run mock analysis",
        "Export structured findings",
    ]
    page_structure = _as_list(
        prototype_plan.get("page_structure"),
        ["Set up task", "Review input", "Run mock analysis", "Export results"],
    )
    user_inputs = _as_list(
        prototype_plan.get("user_inputs"),
        [f"{template} input", "Decision context"],
    )
    system_outputs = _as_list(
        prototype_plan.get("system_outputs"),
        ["Summary result", "Structured detail", "Downloadable JSON"],
    )
    mock_result_preview = (
        prototype_plan.get("mock_result")
        if isinstance(prototype_plan.get("mock_result"), dict)
        else {}
    )
    dynamic_input_block = _build_dynamic_input_block(user_inputs)
    plan_excerpt = (frontend_plan or "Mock-first workflow").strip()[:1000]
    return f'''"""Generated PaperPilot {template} product prototype."""

from __future__ import annotations

import json

import streamlit as st

from adapter import ModelAdapter


PRODUCT_NAME = {product_name!r}
CORE_FEATURES = {core_features!r}
PAGE_STRUCTURE = {page_structure!r}
USER_INPUTS = {user_inputs!r}
SYSTEM_OUTPUTS = {system_outputs!r}
MOCK_RESULT_PREVIEW = {mock_result_preview!r}
FRONTEND_PLAN = {plan_excerpt!r}


st.set_page_config(page_title=PRODUCT_NAME, layout="wide")
st.markdown("""
<style>
.pp-panel {{border: 1px solid #dde3ea; border-radius: 8px; padding: 1rem; background: #fbfcfe; min-height: 5.5rem;}}
.pp-muted {{color: #5f6b7a; font-size: 0.92rem;}}
</style>
""", unsafe_allow_html=True)

with st.sidebar:
    st.header("Run Settings")
    # ModelAdapter defaults to mock_mode=True; keep this visible for review.
    mock_mode = st.toggle("Mock mode", value=True)
    confidence_threshold = st.slider("Confidence threshold", 0.0, 1.0, 0.65, 0.05)
    output_detail = st.selectbox("Output detail", ["Concise", "Detailed"])
    st.caption("Real model integration requires manual adapter.py review.")

st.title(PRODUCT_NAME)
st.caption(
    "Mock-first research product prototype. It demonstrates the product "
    "workflow without importing or executing the source repository."
)

st.markdown("### Core Workflow")
feature_columns = st.columns(min(len(CORE_FEATURES), 3))
for index, feature in enumerate(CORE_FEATURES):
    with feature_columns[index % len(feature_columns)]:
        st.markdown(
            f"<div class='pp-panel'><strong>{{feature}}</strong></div>",
            unsafe_allow_html=True,
        )

st.markdown("### Workflow Map")
for step_number, section in enumerate(PAGE_STRUCTURE, 1):
    st.markdown(f"{{step_number}}. {{section}}")

{dynamic_input_block}

{_INPUT_BLOCKS[template].strip()}

notes = st.text_area(
    "Decision context",
    placeholder="Optional constraints, user segment, or scenario.",
)

if st.button(button_label, type="primary", disabled=run_disabled):
    try:
        adapter = ModelAdapter(mock_mode=mock_mode)
        adapter.setup()
        adapter.load_model()
        result = adapter.predict(
            {{
                "primary_input": input_data,
                "context": context_values,
                "notes": notes,
            }}
        )
    except Exception as exc:
        st.error(f"Product execution failed: {{exc}}")
    else:
        result.update(
            {{
                "confidence_threshold": confidence_threshold,
                "output_detail": output_detail,
                "configured_inputs": context_values,
                "notes": notes,
            }}
        )
        summary_tab, evidence_tab, export_tab = st.tabs(
            ["Summary", "Evidence & Limits", "Export"]
        )
        with summary_tab:
            metric_cols = st.columns(3)
            metric_cols[0].metric("Mode", "Mock" if mock_mode else "Manual integration")
            metric_cols[1].metric("Threshold", f"{{confidence_threshold:.2f}}")
            metric_cols[2].metric("Detail", output_detail)
            st.markdown("#### Expected Outputs")
            for output in SYSTEM_OUTPUTS:
                st.markdown(f"- {{output}}")
            if MOCK_RESULT_PREVIEW:
                st.markdown("#### Planned Mock Fields")
                st.json(MOCK_RESULT_PREVIEW)
            st.json(result)
        with evidence_tab:
            st.markdown("#### Prototype Plan")
            st.markdown(FRONTEND_PLAN)
            st.markdown("#### Limitations")
            st.markdown(
                "- Outputs are deterministic mock responses.\\n"
                "- Real checkpoints, datasets, and repository scripts are not executed.\\n"
                "- Adapter integration must be reviewed manually."
            )
        with export_tab:
            st.write("Download the structured mock result for review or demo notes.")
        result_json = json.dumps(result, ensure_ascii=False, indent=2)
        st.download_button(
            "Download result",
            data=result_json,
            file_name="product_result.json",
            mime="application/json",
        )
'''


def build_adapter_source(
    template_type: str,
    repo_path: str | Path,
    prototype_plan: dict[str, Any] | None = None,
) -> str:
    """Return a mock-first adapter without importing or executing source code."""
    template = _normalize_template(template_type)
    safe_repo_path = repr(str(repo_path))
    prototype_plan = prototype_plan or {}
    mock_result = prototype_plan.get("mock_result")
    if isinstance(mock_result, dict) and mock_result:
        mock_result_source = repr({"type": template, **mock_result})
    else:
        mock_result_source = _MOCK_RESULTS[template]
    return f'''"""Mock-first adapter generated by PaperPilot."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


class ModelAdapter:
    def __init__(
        self,
        repo_path: str = {safe_repo_path},
        device: str = "cpu",
        mock_mode: bool = True,
    ) -> None:
        self.repo_path = Path(repo_path).expanduser()
        self.device = device
        self.mock_mode = mock_mode
        self.model: Any | None = None

    def setup(self) -> dict[str, Any]:
        """Check paths, dependencies, and runtime mode."""
        if not self.mock_mode and not self.repo_path.exists():
            raise FileNotFoundError(f"Repository path not found: {{self.repo_path}}")
        return {{
            "ready": True,
            "mock_mode": self.mock_mode,
            "repo_path": str(self.repo_path),
            "device": self.device,
        }}

    def load_model(self) -> Any | None:
        """Load a reviewed real integration or keep mock mode active."""
        if self.mock_mode:
            return None
        raise NotImplementedError(
            "Real model integration is not configured. Review the source "
            "repository inference code and implement it here manually."
        )

    def _summarize_input(self, value: Any) -> Any:
        """Convert Streamlit inputs into deterministic, displayable metadata."""
        if isinstance(value, dict):
            return {{
                str(key): self._summarize_input(item)
                for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
            }}
        if isinstance(value, (list, tuple)):
            return [self._summarize_input(item) for item in value]
        if isinstance(value, str):
            return {{
                "kind": "text",
                "characters": len(value),
                "preview": value[:160],
            }}
        if isinstance(value, bytes):
            return {{"kind": "bytes", "bytes": len(value)}}
        file_name = str(getattr(value, "name", "") or "")
        if file_name:
            size = getattr(value, "size", None)
            if size is None and hasattr(value, "getbuffer"):
                try:
                    size = len(value.getbuffer())
                except Exception:
                    size = None
            return {{
                "kind": "uploaded_file",
                "name": file_name,
                "content_type": str(getattr(value, "type", "") or ""),
                "size_bytes": size,
            }}
        if value is None:
            return {{"kind": "empty"}}
        return {{"kind": type(value).__name__, "value": str(value)[:160]}}

    def _stable_signature(self, summary: Any) -> str:
        payload = json.dumps(summary, ensure_ascii=True, sort_keys=True, default=str)
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]

    def _base_mock_result(self) -> dict[str, Any]:
        return {mock_result_source}

    def predict(self, input_data: Any) -> dict[str, Any]:
        """Run reviewed inference or return an input-aware deterministic mock result."""
        if not self.mock_mode:
            raise NotImplementedError(
                "Real prediction is not configured. Enable it only after "
                "manual review and implementation."
            )
        input_summary = self._summarize_input(input_data)
        input_signature = self._stable_signature(input_summary)
        result = dict(self._base_mock_result())
        result["input_summary"] = input_summary
        result["input_signature"] = input_signature
        result.setdefault("message", "Mock analysis completed.")
        if isinstance(result.get("result"), dict):
            result["result"] = {{
                **result["result"],
                "input_signature": input_signature,
            }}
        elif isinstance(result.get("result"), str):
            result["result"] = (
                f"{{result['result']}} Input signature: {{input_signature}}."
            )
        else:
            result["result"] = (
                f"Processed {template} input with signature {{input_signature}}."
            )
        return result
'''
