"""Generate a small, inspectable implementation from structured paper evidence."""

from __future__ import annotations

import json
from typing import Any

from agents.structured_agent import StructuredAgent
from schemas.reproduction_schema import (
    GeneratedCodeFile,
    ImplementationBundle,
    ResourceLink,
)
from tools.llm_client import LLMClient


class ReproductionImplementationAgent(StructuredAgent[ImplementationBundle]):
    """Turn paper understanding and a reproduction plan into runnable code."""

    def __init__(self, llm_client: LLMClient | None = None) -> None:
        super().__init__(
            name="Reproduction Implementation Agent",
            prompt_path="reproduction_implementation_prompt.txt",
            schema_type=ImplementationBundle,
            guideline_names=("reproduction_checklist.md", "safety_rules.md"),
            llm_client=llm_client,
        )

    def build_mock(self, input_data: dict[str, Any]) -> ImplementationBundle:
        resources = [
            ResourceLink.model_validate(item)
            for item in input_data.get("approved_resource_links", [])
        ]
        unavailable_reason = (
            "Mock Mode generated a runnable scaffold, but no LLM implemented "
            "the paper method."
            if self.llm_client.mock_mode
            else "The real implementation agent failed, so PaperPilot generated "
            "a runnable fallback scaffold."
        )
        files = [
            GeneratedCodeFile(
                path="README.md",
                purpose="Document the generated scaffold and its limitations.",
                content=(
                    "# PaperPilot Mock Reproduction\n\n"
                    f"{unavailable_reason}\n\n"
                    "Run `python main.py --smoke-test` to validate the scaffold.\n"
                    + (
                        "\nRun `python scripts/download_data.py` to preview verified "
                        "resource downloads, then add `--execute` after review.\n"
                        if resources
                        else ""
                    )
                ),
            ),
            GeneratedCodeFile(
                path="main.py",
                purpose="Provide a safe smoke-test entry point.",
                content=(
                    '"""Runnable placeholder generated by PaperPilot Mock Mode."""\n\n'
                    "import argparse\n\n\n"
                    "def main() -> None:\n"
                    '    parser = argparse.ArgumentParser(description="PaperPilot reproduction scaffold")\n'
                    '    parser.add_argument("--smoke-test", action="store_true")\n'
                    "    args = parser.parse_args()\n"
                    "    if args.smoke_test:\n"
                    '        print("PaperPilot mock reproduction smoke test passed.")\n\n\n'
                    'if __name__ == "__main__":\n'
                    "    main()\n"
                ),
            ),
            GeneratedCodeFile(
                path="requirements.txt",
                purpose="Declare the minimal dependency set.",
                content="# Add paper-specific dependencies after disabling Mock Mode.\n",
            ),
            GeneratedCodeFile(
                path="tests/test_smoke.py",
                purpose="Verify the generated entry point imports.",
                content=(
                    "from main import main\n\n\n"
                    "def test_main_is_callable() -> None:\n"
                    "    assert callable(main)\n"
                ),
            ),
        ]
        if resources:
            files.append(
                GeneratedCodeFile(
                    path="scripts/download_data.py",
                    purpose="Preview and explicitly download evidence-backed resources.",
                    content=self._mock_download_script(resources),
                )
            )
        return ImplementationBundle(
            project_name="paperpilot_mock_reproduction",
            summary=unavailable_reason,
            fidelity_scope=["Pipeline and smoke-test structure only."],
            assumptions=["The real paper method remains unimplemented."],
            data_resources=resources,
            files=files,
            data_download_command=(
                "python scripts/download_data.py --execute" if resources else ""
            ),
            smoke_test_command="python main.py --smoke-test",
            expected_smoke_test_output="PaperPilot mock reproduction smoke test passed.",
        )

    @staticmethod
    def _mock_download_script(resources: list[ResourceLink]) -> str:
        resource_data = [
            {
                "name": item.name,
                "url": item.url,
                "destination": item.destination,
            }
            for item in resources
        ]
        return f'''"""Preview or download evidence-backed paper resources."""

import argparse
import shutil
from pathlib import Path
from urllib.request import urlopen


RESOURCES = {json.dumps(resource_data, ensure_ascii=True, indent=4)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Download verified paper resources")
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Perform downloads. Without this flag, only print the download plan.",
    )
    args = parser.parse_args()
    for resource in RESOURCES:
        destination = Path(resource["destination"])
        print(f'{{resource["name"]}}: {{resource["url"]}} -> {{destination}}')
        if not args.execute:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        with urlopen(resource["url"]) as response, destination.open("wb") as output:
            shutil.copyfileobj(response, output)


if __name__ == "__main__":
    main()
'''

    @classmethod
    def _apply_approved_resources(
        cls,
        result: ImplementationBundle,
        input_data: dict[str, Any],
    ) -> None:
        """Replace model-authored download metadata with deterministic safe files."""
        resources = [
            ResourceLink.model_validate(item)
            for item in input_data.get("approved_resource_links", [])
        ]
        result.files = [
            item
            for item in result.files
            if item.path.strip().replace("\\", "/").lower() != "scripts/download_data.py"
        ]
        result.data_resources = resources
        result.data_download_command = ""
        if resources:
            result.files.append(
                GeneratedCodeFile(
                    path="scripts/download_data.py",
                    purpose="Preview and explicitly download evidence-backed resources.",
                    content=cls._mock_download_script(resources),
                )
            )
            result.data_download_command = "python scripts/download_data.py --execute"

    @staticmethod
    def _markdown_bullets(items: list[str], empty: str) -> str:
        return "\n".join(f"- {item}" for item in items) if items else f"- {empty}"

    @classmethod
    def _apply_required_scaffold(cls, result: ImplementationBundle) -> None:
        """Add required project metadata without replacing model-generated code."""
        for item in result.files:
            if not item.purpose.strip():
                item.purpose = "Model-generated reproduction project file."

        normalized_paths = {
            item.path.strip().replace("\\", "/").lower() for item in result.files
        }
        if "readme.md" not in normalized_paths:
            generated_files = cls._markdown_bullets(
                [f"`{item.path}`: {item.purpose}" for item in result.files],
                "No model-generated files were listed.",
            )
            result.files.append(
                GeneratedCodeFile(
                    path="README.md",
                    purpose="Document the generated implementation and how to inspect it.",
                    content=f"""# {result.project_name or "PaperPilot Reproduction"}

## Summary
{result.summary}

## Fidelity Scope
{cls._markdown_bullets(result.fidelity_scope, "Not specified by the model.")}

## Assumptions
{cls._markdown_bullets(result.assumptions, "Not specified by the model.")}

## Generated Files
{generated_files}

## Validation
Run `{result.smoke_test_command or "python main.py --smoke-test"}` after reviewing the generated code.

This is a PaperPilot-generated approximation, not an official implementation
or evidence that the paper's reported metrics were reproduced.
""",
                )
            )
            normalized_paths.add("readme.md")

        if "main.py" not in normalized_paths:
            result.files.append(
                GeneratedCodeFile(
                    path="main.py",
                    purpose="Provide a safe generated-project smoke-test entry point.",
                    content=(
                        '"""Safe entry point added by PaperPilot."""\n\n'
                        "import argparse\n\n\n"
                        "def main() -> None:\n"
                        "    parser = argparse.ArgumentParser()\n"
                        '    parser.add_argument("--smoke-test", action="store_true")\n'
                        "    args = parser.parse_args()\n"
                        "    if args.smoke_test:\n"
                        '        print("Generated reproduction project is importable.")\n\n\n'
                        'if __name__ == "__main__":\n'
                        "    main()\n"
                    ),
                )
            )
            normalized_paths.add("main.py")

        if not any(
            path.startswith("tests/") and path.endswith(".py")
            for path in normalized_paths
        ):
            result.files.append(
                GeneratedCodeFile(
                    path="tests/test_generated_project.py",
                    purpose="Verify the generated project includes its required entry point.",
                    content=(
                        "from pathlib import Path\n\n\n"
                        "def test_generated_project_has_entrypoint() -> None:\n"
                        '    assert Path("main.py").is_file()\n'
                    ),
                )
            )
        if not result.smoke_test_command.strip():
            result.smoke_test_command = "python main.py --smoke-test"

    def validate_structured_result(
        self,
        result: ImplementationBundle,
        input_data: dict[str, Any],
    ) -> str | None:
        self._apply_approved_resources(result, input_data)
        if not result.summary.strip():
            return "implementation summary is empty"
        if not result.files:
            return "implementation contains no files"
        self._apply_required_scaffold(result)
        paths = {
            item.path.strip().replace("\\", "/").lower() for item in result.files
        }
        if not any(path.endswith(".py") for path in paths):
            return "implementation must include at least one Python file"
        return None
