import {
  Bot,
  Boxes,
  ClipboardCheck,
  Code2,
  FileText,
  FolderGit2,
  GitBranch,
  Hammer,
  LayoutDashboard,
  ListChecks,
  Play,
  Search,
  ShieldCheck,
  Terminal,
  UserCheck,
} from "lucide-react";

export const icons = {
  projects: Boxes,
  papers: FileText,
  repos: FolderGit2,
  runs: Play,
  agents: Bot,
  settings: LayoutDashboard,

  parse_paper: FileText,
  parse: FileText,
  research_understanding: Search,
  research_evidence: Search,
  prepare_repository: FolderGit2,
  repository_understanding: GitBranch,
  repo_evidence: GitBranch,
  reproduction_planner: ListChecks,
  planning: ListChecks,
  command_routing: ShieldCheck,
  reproduction_implementation: Code2,
  implementation: Code2,
  sandbox_verify: ShieldCheck,
  code_review: ClipboardCheck,
  review: ClipboardCheck,
  code_revise: Hammer,
  revision: Hammer,
  execution_diagnosis: Terminal,
  diagnosis: Terminal,

  capability_cards: FileText,
  capability_map: GitBranch,
  method_composition: Boxes,
  jtbd: Search,
  prd: ListChecks,
  mvp: ClipboardCheck,
  product_planner: ListChecks,
  prototype_builder: Code2,
  prototype: Code2,
  product_evaluator: ClipboardCheck,
  evaluation: ClipboardCheck,
  scaffold: Boxes,
  outputs: FileText,
  approval: UserCheck,
} as const;
